name: ci
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.13"]
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v5.2.2
      - run: uv pip install -e ".[dev]" --system
      - run: pytest -q
